import {
  Bell,
  Briefcase,
  ChevronDown,
  DollarSign,
  Headset,
  House,
  LogOut,
  MessageCircle,
  Repeat,
  Settings,
  Users,
  Webhook,
} from "lucide-react"

export {
  EyeOpenIcon,
  EyeNoneIcon as EyeCloseIcon,
  SunIcon,
  MoonIcon,
  ExclamationTriangleIcon,
  ExitIcon,
  EnterIcon,
  GearIcon,
  RocketIcon,
  PlusIcon,
  HamburgerMenuIcon,
  Pencil2Icon,
  UpdateIcon,
  CheckCircledIcon,
  PlayIcon,
  TrashIcon,
  ArchiveIcon,
  ResetIcon,
  FileTextIcon,
  IdCardIcon,
  PlusCircledIcon,
  FilePlusIcon,
  CheckIcon,
  ChevronLeftIcon,
  ChevronRightIcon,
  DotsHorizontalIcon,
  ArrowLeftIcon,
} from "@radix-ui/react-icons"

export const Icons = {
  webhook: Webhook,
  house: House,
  briefcase: Briefcase,
  headset: Headset,
  messagecircle: MessageCircle,
  settings: Settings,
  logout: LogOut,
  dollarSign: DollarSign,
  users: Users,
  repeat: Repeat,
  chevronsDown: ChevronDown,
  bell: Bell,
}
